### ISSUE TITLE
连续调用同一个接口，只有第一次成功，其余都报错

### ISSUE THREAD

**Issue by asiareal** [flftfqwxf/mockserver#20]
## DESC
我连续调用了同一个接口，发现只有第一次成功，其余2次都报错了
```js
api.getMyInfo()  // 请求了一个mockserver地址
api.getMyInfo()
api.getMyInfo()
```
报错信息如下：
```
5|developm | [2017-12-06 17:37:50] [Error] SyntaxError: Unexpected token o in JSON at position 1
5|developm |     at Object.parse (native)
5|developm |     at _class._callee$ (/Users/wangyazhou/code/github/mockserver/src/api/controller/index.js:90:41)
5|developm |     at tryCatch (/Users/wangyazhou/code/github/mockserver/node_modules/regenerator-runtime/runtime.js:65:40)
5|developm |     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/wangyazhou/code/github/mockserver/node_modules/regenerator-runtime/runtime.js:299:22)
5|developm |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/wangyazhou/code/github/mockserver/node_modules/regenerator-runtime/runtime.js:117:21)
5|developm |     at step (/Users/wangyazhou/code/github/mockserver/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
5|developm |     at /Users/wangyazhou/code/github/mockserver/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
5|developm | [2017-12-06 17:37:50] [Error] SyntaxError: Unexpected token o in JSON at position 1
5|developm |     at Object.parse (native)
5|developm |     at _class._callee$ (/Users/wangyazhou/code/github/mockserver/src/api/controller/index.js:90:41)
5|developm |     at tryCatch (/Users/wangyazhou/code/github/mockserver/node_modules/regenerator-runtime/runtime.js:65:40)
5|developm |     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/wangyazhou/code/github/mockserver/node_modules/regenerator-runtime/runtime.js:299:22)
5|developm |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/wangyazhou/code/github/mockserver/node_modules/regenerator-runtime/runtime.js:117:21)
5|developm |     at step (/Users/wangyazhou/code/github/mockserver/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
5|developm |     at /Users/wangyazhou/code/github/mockserver/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

## ENV

Platform: mac pro

Node.js Version:  v6.11.5

mockserver Version: 2.3.2

**Comment by flftfqwxf** [comment]
fixed #20
